run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gofmt
    - goimports
    - misspell

linters-settings:
  errcheck:
    exclude-functions:
      - (io.Closer).Close
      - (net/http.ResponseWriter).Write
  goimports:
    local-prefixes: github.com/nehemiyawicks/opsentry

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
